server {
    listen 185.252.29.27:80;
    server_name tmessenger.taavonafarin.ir;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/tmessenger-acme;
    }
    location / {
        return 301 https://tmessenger.taavonafarin.ir$request_uri;
    }
}
